// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fetch} from '../models';
import {types} from '../models';
import {shared} from '../models';

export function CancelDownloads():Promise<void>;

export function GetHomeDirectory():Promise<string>;

export function IsOutdated():Promise<boolean>;

export function OnExtractorFound(arg1:string):Promise<void>;

export function OnExtractorTypeFound(arg1:string,arg2:string):Promise<void>;

export function OnMediaDownloaded(arg1:number,arg2:Array<fetch.Response>):Promise<void>;

export function OnMediaQueried(arg1:number):Promise<void>;

export function OnQueryCompleted(arg1:number,arg2:boolean):Promise<void>;

export function OpenCookiesPath(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<string>;

export function QueryMedia(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:boolean,arg6:string,arg7:string,arg8:boolean):Promise<Array<types.Media>>;

export function StartDownload(arg1:Array<types.Media>,arg2:string,arg3:number):Promise<Array<shared.Download>>;

export function StopQuery():Promise<void>;
